aplicaciones/registrados/urls.py
from django.urls import path
from . import views

app_name='usuarios_app'
urlpatterns = [
    path('register/',views.Registerview.as_view(),name='register'),
    path('verif/<pk>',views.Codeverify.as_view(),name='verification'),
    path('login/', views.Loginview.as_view(), name='login'),
    path('logout/', views.Logoutview.as_view(), name='logoutuser'),
    path('update-pass/', views.Updatepass.as_view(), name='update-pass'),
    path('account/', views.Accountview.as_view(), name='account'),
    path('updt/<pk>', views.Updateallview.as_view(), name='update-all'),
]

web_exordium/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('aplicaciones.registrados.urls',namespace='usuarios_app')),
    path('',include('aplicaciones.indic.urls',namespace='indic_app')),
    path('clima/',include('aplicaciones.clima.urls',namespace='clima_app')),
    path('stopwatch/', include('aplicaciones.crono.urls', namespace='crono_app')),
    path('tweets/',include('aplicaciones.tweets.urls',namespace='tweets_app')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aplicaciones/registrados/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import Usuario_Mang
from PIL import Image
from django.db.models.signals import post_save
from django.utils import timezone

class Usuario(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES=(
        ('M','Masculino'),('F','Femenino'),('O','otros')
    )

    email=models.EmailField('Email', unique=True,help_text='Required field from models')
    name = models.CharField('Name', max_length=60)
    last_name=models.CharField('Last name',max_length=60)
    country=models.CharField('Nacionality',max_length=50,blank=True)
    gender=models.CharField('Gender', max_length=1,choices=GENDER_CHOICES,blank=True)
    date_birth=models.DateField('Date of Birth', blank=True,null=True)
    code_reg=models.CharField(max_length=6,blank=True)
    photo=models.ImageField(upload_to='profile',default='default.png',blank=True,null=True)
    is_staff=models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    date_reg=models.DateField('Register Date', default=timezone.now)
    last_mod=models.DateField('Last Modified', auto_now=True) #debido al auto_now esto no se va a mostrar en el admin site, no es editable
    objects=Usuario_Mang()

    USERNAME_FIELD='email'
    REQUIRED_FIELDS = ['name','last_name']


    def get_short_name(self):
        return self.name
    def get_full_name(self):
        return self.name + ' ' + self.last_name

    def __str__(self):
        return self.email + '-'+self.name

    class Meta:
        verbose_name='Usuario'
        verbose_name_plural='Usuarios'

def optimize_img(sender, instance, **kwargs):
    if instance.photo:
        photo = Image.open(instance.photo.path)
        photo.save(instance.photo.path,quality=20,optimize=True)



post_save.connect(optimize_img,sender=Usuario)

templates/usuarios/account.html
{% extends 'comunes/layout.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'registrados/estilo.css' %}">
{% endblock %}
{% block titulo %}
    Account
{% endblock %}
{% block body %}
    <div class="ghost titulo-acc">Información de la cuenta</div>
{#    <h2 class="titulo-acc">Información de la cuenta</h2>#}
    <div class="user">
        <div class="image"><img src="{% static 'comun/default.png' %}" alt="" class="imagen"></div>
        <div class="data">
            <table>
                <tr>
                    <td><b>Name:</b></td>
                    <td>{{ data.name }}</td>
                </tr>
                <tr>
                    <td><b>Last Name:</b></td>
                    <td>{{ data.last_name }}</td>
                </tr>
                <tr>
                    <td><b>Email:</b></td>
                    <td>{{ data.email }}</td>
                </tr>
                <tr>
                    <td><b>Gender:</b></td>
                    <td id="gender">{{ data.gender }}</td>
                </tr>
                <tr>
                    <td><b>Birth:</b></td>
                    <td id="birth">{{ data.date_birth }}</td>
                </tr>
                <tr>
                    <td><b>Registered:</b></td>
                    <td>{{ data.date_reg }}</td>
                </tr>
                <tr>
                    <td><b>Last Modification:</b></td>
                    <td>{{ data.last_mod }}</td>
                </tr>
            </table>

        </div>

    </div>
    <div class="boxbutton"><a href="{% url 'usuarios_app:update-all' data.id %}" class="btn btn-one"><span>editar</span></a></div>


    <script src="{% static 'registrados/account.js' %}"></script>
{% endblock %}

templates/usuarios/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block titulo %}

    {% endblock %}</title>
    {% block head %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'registrados/estilo.css' %}">
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

templates/usuarios/login.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'registrados/estilo.css' %}">
{% endblock %}

{% block titulo %}
Log in
{% endblock %}
{% block body %}
    <div class="ghost"></div>
    <div class="loginsc">
    <div class="loginform">
        <form method="post">
    {% csrf_token %}
            <div class="group">
      {{ form.mail }}
      <span class="highlight"></span>
      <span class="bar"></span>
      <label class="name">Email</label>
    </div>

    <div class="group">
      {{ form.passw }}
      <span class="highlight"></span>
      <span class="bar"></span>
      <label class="name">Password</label>
    </div>
{#    {{ form.as_p }}#}
            <div class="estilohov">
                <button type="submit" class="log-button">login</button>
            </div>

    </form>
    </div>
    <div class="loginimg">
        <img src="{% static 'registrados/log-fondo.jpg' %}" alt="" class="imglog">
    </div>
    </div>

{#    <h1>{% lorem 20 %}</h1>#}

{% endblock %}

templates/usuarios/registro.html
{% extends 'comunes/layout.html' %}
{% block title %}
Registro
{% endblock %}
{% block body %}
    <div class="ghost"></div>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit">Create user</button>
    </form>
{% endblock %}

templates/usuarios/updtall.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}

    <link rel="stylesheet" href="{% static 'registrados/estilo.css' %}">

{% endblock %}

{% block titulo %}
    Update all
{% endblock %}
{% block body %}
    <div class="ghost"></div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="box-content">
            <div class="boxf">
                {{ form.email.label }}
                {{ form.email }}
            </div>
            <div class="boxf">
                {{ form.name.label }}
                {{ form.name }}
            </div>
            <div class="boxf">
                {{ form.last_name.label }}
                {{ form.last_name }}
            </div>
            <div class="boxf">
                {{ form.country.label }}
                {{ form.country }}
            </div>
            <div class="boxf">
                {{ form.gender.label }}
                {{ form.gender }}
            </div>
            <div class="boxf">
                {{ form.date_birth.label }}
                {{ form.date_birth }}
            </div>
{#            <div class="boxf">#}
{#                {{ form.photo.label }}#}
{#                <label for="id_photo">#}
{#                <div class="buttonn">#}
{##}
{#                        <div class="face1">#}
{#                            select image#}
{#                        </div>#}
{#                    <div class="face2">#}
{#                        <i class="bi bi-cloud-arrow-up-fill"></i>#}
{#                    </div>#}
{##}
{#                </div></label>#}
{#                {{ form.photo }}#}
{##}
{#            </div>#}
            <div class="updbox">
                <button type="submit" class="updbutton"><span>Update</span></button>

            </div>
        </div>

    </form>
    {% lorem 40 %}
    <script src="{% static 'registrados/updall.js' %}"></script>
{% endblock %}
{#fields=('email','name','last_name','country','gender','date_birth','photo')#}

templates/usuarios/updtpss.html
{% extends 'comunes/layout.html' %}

{% block titulo %}
Change Password
{% endblock %}
{% block body %}
    <div class="ghost"></div>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit">Change pass</button>
    </form>
{% endblock %}

templates/usuarios/verify.html
{% extends 'comunes/layout.html' %}

{% block titulo %}
verificacion
{% endblock %}
{% block body %}
    <div class="ghost"></div>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit">verificar</button>
    </form>
{% endblock %}