aplicaciones/crono/urls.py
from django.urls import path
from . import views

app_name='crono_app'
urlpatterns = [
    path('stopwatch/',views.Cronoview.as_view(),name='cronometro'),
    path('watch/',views.Relojview.as_view(),name='reloj'),
]

web_exordium/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('aplicaciones.registrados.urls',namespace='usuarios_app')),
    path('',include('aplicaciones.indic.urls',namespace='indic_app')),
    path('clima/',include('aplicaciones.clima.urls',namespace='clima_app')),
    path('stopwatch/', include('aplicaciones.crono.urls', namespace='crono_app')),
    path('tweets/',include('aplicaciones.tweets.urls',namespace='tweets_app')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aplicaciones/crono/models.py
from django.db import models

# Create your models here.

aplicaciones/crono/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from geopy.geocoders import Nominatim

# Create your views here.

class Cronoview(TemplateView):
    template_name = 'crono/cronometro.html'

class Relojview(TemplateView):
    template_name = 'crono/reloj.html'

templates/crono/cronometro.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crono/crono_est.css' %}">
{% endblock %}
{% block titulo %}
    StopWatch
{% endblock %}
{% block body %}
{#    <div class="ghost"></div>#}
    <div class="rj_lateral" id="lateral">
        <ul class="lateral_list">
            <li class="lat_item">
                <a href="{% url 'crono_app:reloj' %}" class="world_t">
                    <span id="world_t">
                        <i class="bi bi-globe2"></i></span>
                </a>
            </li>

            <li class="lat_item">
                <a href="{% url 'crono_app:cronometro' %}" class="stop_w">
                    <span id="stop_w">
                        <i class="bi bi-stopwatch-fill"></i>
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="crono_total">
        <h1>cronometro</h1>


        <div class="crono">
            <p id="tiempo"><span class="big_number" id="big_number">00:00:00</span><span class="small_number"
                                                                                 id="small_number">.000</span></p>
            <input type="button" id="iniciar" value="iniciar" class="buttn">
            <input type="button" id="parar" value="parar" class="buttn escondido">
            <input type="button" id="reset" value="reset" class="buttn">
            <input type="button" id="vuelta_btn" value="vuelta" class="buttn escondido">
        </div>
        <div id="vueltas" class="vueltas escondido">
            <table id="tabla_vlt">
                <tr>
                    <th>
                        Lap
                    </th>
                    <th>
                        Lap time
                    </th>
                    <th>
                        Total time
                    </th>
                </tr>


            </table>
        </div>

    </div>
    <script src="{% static 'crono/crono_js.js' %}"></script>
{% endblock %}

templates/crono/reloj.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'crono/crono_est.css' %}">
{% endblock %}
{% block titulo %}
    watch
{% endblock %}
{% block body %}
    <div class="rj_lateral" id="lateral">
        <ul class="lateral_list">
            <li class="lat_item">
                <a href="{% url 'crono_app:reloj' %}" class="world_t">
                    <span id="world_t">
                        <i class="bi bi-globe2"></i></span>
                </a>
            </li>

            <li class="lat_item">
                <a href="{% url 'crono_app:cronometro' %}" class="stop_w">
                    <span id="stop_w">
                        <i class="bi bi-stopwatch-fill"></i>
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="rj_contenido">
    <h1>World time</h1>
    <div id="rj_reloj" class="rj_reloj">
        <span id="rj_lugar_local" class="rj_lugar_local"></span> <br>
        <span id="rj_hora" class="rj_hora">00:00:00</span><span id="rj_hora_pm"></span>
    </div>
    </div>

    <script src="{% static 'crono/reloj_js.js' %}"></script>
{% endblock %}