aplicaciones/clima/urls.py
from django.urls import path
from . import views

app_name='clima_app'
urlpatterns = [
    path('busqueda/',views.Climaview.as_view(),name='clima'),
]

aplicaciones/crono/urls.py
from django.urls import path
from . import views

app_name='crono_app'
urlpatterns = [
    path('stopwatch/',views.Cronoview.as_view(),name='cronometro'),
    path('watch/',views.Relojview.as_view(),name='reloj'),
]

aplicaciones/indic/urls.py
from django.urls import path
from . import views

app_name='indic_app'
urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('about/',views.Aboutus.as_view(),name='about'),
    path('contact/', views.contacto.as_view(), name='contacto'),
]

aplicaciones/tweets/urls.py
from django.urls import path
from . import views

app_name='tweets_app'
urlpatterns = [
    path('', views.home_view, name='home_tweet'),
    path('tweets', views.tweet_list_view, name='tweet_list'),
    path('create-tweet', views.tweet_create_view, name='tweet_create'),

    path('tweets/<int:tweet_id>',views.home_view_details,name='home_det_tweet'),

]

web_exordium/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('aplicaciones.registrados.urls',namespace='usuarios_app')),
    path('',include('aplicaciones.indic.urls',namespace='indic_app')),
    path('clima/',include('aplicaciones.clima.urls',namespace='clima_app')),
    path('stopwatch/', include('aplicaciones.crono.urls', namespace='crono_app')),
    path('tweets/',include('aplicaciones.tweets.urls',namespace='tweets_app')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aplicaciones/indic/models.py
from django.db import models

# Create your models here.

aplicaciones/indic/forms.py
from django import forms

class Contactform(forms.Form):
    email=forms.EmailField(label='Email',help_text='*Required',required=True,
                           widget=forms.EmailInput(attrs={'placeholder':'Required','class':'cont mail'}))
    subject=forms.CharField(label='Subject',help_text='What do you want to talk about',required=True,
                            widget=forms.TextInput(attrs={'placeholder':'i.e. Bug founded','class':'cont subj'}))
    message=forms.CharField(label='Message',required=True,widget=forms.Textarea(
        attrs={'cols':'40','rows':'10','class':'cont messag','placeholder':'What do you Think?'}))

aplicaciones/indic/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.views.generic import TemplateView,FormView
from .forms import Contactform
from django.urls import reverse_lazy

# Create your views here.

class Index(TemplateView):
    template_name = 'indic/index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        if self.request.GET.get('mensajes',''):
            context['mensajes'] = self.request.GET.get('mensajes','')
        return context






class Aboutus(TemplateView):
    template_name = 'indic/about.html'

class contacto(FormView):
    template_name = 'indic/contacto.html'
    form_class = Contactform
    success_url = '/'

    def form_valid(self, form):
        mail=form.cleaned_data['email']
        asunt=form.cleaned_data['subject']
        messag=form.cleaned_data['message']
        send_mail(asunt,messag+' '+mail,mail,['omarramirezq@hotmail.com',])
        return redirect('/?mensajes=mensaje+enviado')
        # return reverse_lazy('indic_app:index',Kwargs={'mensajes':'mensaje enviado bien'})

templates/indic/about.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'indic/estiloindic.css' %}">
{% endblock %}
{% block titulo %}
    About Us
{% endblock %}
{% block body %}
    <div class="contenedor">
        <div class="logotipo">
            <img src="{% static 'indic/logoexordium.svg' %}" alt="" class="logo">
        </div>
        <div class="texto">
            <p class="titulo-about">ABOUT EXORDIUM</p>
            <p class="cuerpo-about">
                This project starts from the simple idea of making a webpage, an online tool for my personal use and ended been
                all of this, either a lot or a little this humble site has been built and designed from scratch, taking care of
                every aspect, mesure and detail, from back to front-end applying everything I have learn in the last six months.
                Exordium means start again, a new beginning after a bad time, life is about it and I see this like a new
                start, again.
            </p>
            <div class="firma">
                <span>designed & created by</span><br>
                <span class="firma-about">Omar Ramirez.</span>
            </div>
        </div>
    </div>
{% endblock %}

templates/indic/contacto.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'indic/estiloindic.css' %}">
{% endblock %}
{% block titulo %}
Contact
{% endblock %}
{% block body %}
{#    <div class="ghost"></div>#}
    <div class="cuadrobg">
    <div class="divform">

        <form action="" method="post" class="forma-contact">
    {% csrf_token %}
        {% for foo in form %}
        {% for error in foo.errors %}
        <p>{{ error }}</p>
        {% endfor %}

        {% endfor %}

    <p class="etiqueta">{{ form.email.label }}&nbsp&nbsp<i class="bi bi-envelope-fill"></i></p>
        <p>{{ form.email }}</p>
        <p class="etiqueta">{{ form.subject.label }}</p>
        <p>{{ form.subject }}</p>
        <p class="etiqueta">{{ form.message.label }}&nbsp&nbsp<i class="bi bi-chat-left-text-fill"></i></p>
        <p>{{ form.message }}</p>


{#        <button type="submit" class="btn-contact">Send &nbsp<i class="bi bi-arrow-up-right-circle-fill"></i></button>#}
        <button type="submit" class="btn-contact"><span>Send</span>
  <svg width="13px" height="10px" viewBox="0 0 13 10">
    <path d="M1,5 L11,5"></path>
    <polyline points="8 1 12 5 8 9"></polyline>
  </svg></button>
    </form>

    </div>

    <div class="contenedor-img">
        <div class="tit-volt">CONTACT US</div>
        <img src="{% static 'indic/captura.PNG' %}" alt="" class="cont-img">
    </div>

    </div>

{% endblock %}

templates/indic/index.html
{% extends 'comunes/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'indic/estiloindic.css' %}">
{% endblock %}
{% block titulo %}
    Start
{% endblock %}
{% block body %}
    <div class="fondo" id="fondo-pantalla">
        {% if mensajes %}
            <span class="mensaje-opt">{{ mensajes }}</span>
        {% endif %}
        <div class="index_menu">
            <div class="index_menu_option">
                <a href="{% url 'clima_app:clima' %}" class="index_link">
                <span class="index_menu_icono">
                <i class="bi bi-cloud-rain-heavy-fill"></i>
                <i class="bi bi-thermometer-half"></i>
                </span>
                <p>Weather App</p></a>
            </div>
            <div class="index_menu_option">
                <a href="{% url 'crono_app:cronometro' %}" class="index_link">
                <span class="index_menu_icono">
                <i class="bi bi-stopwatch-fill"></i>
                <i class="bi bi-clock-fill"></i>
                </span>
                <p>Watch App</p></a>
            </div>
{#            <div class="index_menu_option">#}
{#                <a href="{% url 'tweets_app:home_tweet' %}" class="index_link">#}
{#                <span class="index_menu_icono">#}
{#                <i class="bi bi-twitter"></i>#}
{#                <i class="bi bi-gear-fill"></i>#}
{#                </span>#}
{#                <p>Twitter like app</p></a>#}
{#            </div>#}
            <div class="index_menu_option"></div>
            <div class="index_menu_option"></div>
            <div class="index_menu_option"></div>
            <div class="index_menu_option"></div>
        </div>
    </div>
    {#    <h2>{% lorem 10 %}</h2>#}
    <script src="{% static 'indic/indicjs.js' %}"></script>
{% endblock %}